# Generated by Django 5.0.6 on 2024-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("eid", models.AutoField(primary_key=True, serialize=False)),
                ("ename", models.CharField(max_length=200)),
                ("esalary", models.IntegerField(max_length=50)),
                ("edescription", models.CharField(max_length=200)),
            ],
        ),
    ]
